blank_issues_enabled: false
contact_links:
  - name: Open Mainframe Ambassador application
    url: https://openmainframeproject.org/blog/open-mainframe-project-launches-applications-for-2024-ambassadors/
    about: Apply to be an Open Mainframe Ambassador
